version: "3.7"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    hostname: "rabbitmq"
    volumes:
      - ./etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./logs:/var/log/rabbitmq/log
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - VIRTUAL_HOST=rabbitmq.loc

networks:
  default:
    name: rabbitmq
